/* FUNÇÕES DE AGREGACAO NUMERICAS*/

USE PROJETO;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    JANEIRO FLOAT(10,2),
    FEVEREIRO FLOAT(10, 2)
    
);

INSERT INTO VENDEDORES VALUES(NULL,'CARLOS','M',7878787.48,8848474.87);
INSERT INTO VENDEDORES VALUES(NULL,'MARIA','F',7878787.48,8884848.87);
INSERT INTO VENDEDORES VALUES(NULL,'ANTONIO','M',7878787.48,8484784.87);
INSERT INTO VENDEDORES VALUES(NULL,'CLARA','F',7878787.48,8884847.87);
INSERT INTO VENDEDORES VALUES(NULL,'IVONE','F',7878787.48,8884784.87);
INSERT INTO VENDEDORES VALUES(NULL,'JOAO','F',7878787.48,8884784.87);

/*MAX - TRAZ O VALOR MAXIMO DE UMA COLUNA */

SELECT MAX(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES;

/*MIN - TRAZ O VALOR MINIMO DE UMA COLUNA */

SELECT MIN(FEVEREIRO) AS MENOR_FEV
FROM VENDEDORES;

/*AVG - TRAZ O VALOR MEDIA DE UMA COLUNA */

SELECT AVG(FEVEREIRO) AS MEDIA_FEV
FROM VENDEDORES;

/*VARIAS FUNCOES*/
SELECT MAX(FEVEREIRO) AS MAIOR_FEV,
	MIN(FEVEREIRO) AS MENOR_FEV,
	TRUNCATE(AVG(FEVEREIRO), 2) AS MEDIA_FEV
	FROM VENDEDORES;
    
/*SOMA*/

SELECT SUM(JANEIRO) AS TOTAL_SUM FROM VENDEDORES;

SELECT SUM(FEVEREIRO) AS TOTAL FROM VENDEDORES
GROUP BY SEXO;

/*SUBQUERY*/
/* VENDEOR QUE VENDEU MENOS EM FEVEREIRO
E O SEU NOME*/
SELECT NOME, MIN(FEVEREIRO) AS MIN_MARCO FROM VENDEDORES GROUP BY NOME;
SELECT * FROM VENDEDORES;

SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO = (SELECT MIN(FEVEREIRO) FROM VENDEDORES);

/* VENDEOR QUE VENDEU MAIS EM FEVEREIRO
E O SEU NOME*/
SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO = (SELECT MAX(FEVEREIRO) FROM VENDEDORES);

/* VENDEOR QUE VENDEU MAIS DO QUE A MÉDIA FEVEREIRO
E O SEU NOME*/

SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO < (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

/*OPERAÇÕES EM LINHAS */

SELECT NOME, JANEIRO, FEVEREIRO, (JANEIRO+FEVEREIRO) AS "TOTAL",
TRUNCATE((JANEIRO+FEVEREIRO)/2,2) AS "MEDIA"
FROM VENDEDORES;


