#Filtrando nulos
USE PROJETO;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NOT NULL;

# IS OU IS NOT NULL


/* UPDATE */

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'JORGE@IG.COM.BR'
WHERE NOME = 'JORGE';

UPDATE CLIENTE
SET EMAIL = 'LILIAN@IG.COM.BR'
WHERE NOME = 'LILIAN';

/* DELETANDO REGISTROS COM CLAUSULA DELETE */

#PRIMEIRO CONTAR OS REGISTROS DA TABELA

SELECT * FROM CLIENTE;

#SEGUNDO CONFERIR O DADO A SER APAGADO
SELECT NOME FROM CLIENTE
WHERE NOME = 'ANA';

#TERCEIRO APAGAR
DELETE FROM CLIENTE
WHERE NOME = 'ANA';




