USE COMERCIO;

/* EXERCICIOS DML */

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

/* CADASTRE UM ENDERECO PARA CADA CLIENTE */

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',14);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',16);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',17);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',22);

/* CADASTRE TELEFONES PARA OS CLIENTES */


INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',10);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',10);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',12);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',13);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',14);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',16);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',17);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',20);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',20);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',21);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',21);

SELECT * FROM CLIENTE;
SELECT * FROM ENDERECO;
SELECT * FROM TELEFONE;

/*RELATÓRIO DE TODOS OS CLIENTES*/
SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO FROM CLIENTE
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE;

/*RELATÓRIO DE HOMENS*/
SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO FROM CLIENTE
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE IN (13,14,19,20);

/*RELATÓRIO DE MULHERES*/
SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO FROM CLIENTE
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

UPDATE CLIENTE 
SET SEXO = 'M'
WHERE IDCLIENTE = 17;

/*QUANTIDADE DE HOMENS E MULHERES*/
SELECT COUNT(*) AS QUANTIDADE, SEXO FROM CLIENTE
GROUP BY SEXO;

/*IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NÃO TENHAM CELULAR*/

SELECT IDCLIENTE, EMAIL, NOME, SEXO, T.TIPO, E.BAIRRO, E.CIDADE FROM CLIENTE
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F' AND E.BAIRRO = 'CENTRO' AND E.CIDADE = 'RIO DE JANEIRO'
AND TIPO IN ('RES','COM');

/*PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATÓRIO COM O NOME, EMAIL
E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO RIO DE JANEIRO VOCÊ TERÁ QUE 
PASSAR A QUERY PARA GERAR O RELATÓRIO PARA O PROGRAMADOR*/

SELECT EMAIL, NOME, SEXO, T.TIPO, T.NUMERO FROM CLIENTE
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
WHERE T.TIPO = 'CEL' AND E.ESTADO = 'RJ';


/*PARA UMA CAMPANHA DE PRODUTO DE BELEZA, O COMERCIAL SOLICITOU UM RELATÓRIO
COM NOME, EMAIL E CELULAR DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO
VOCÊ TERÁ QUE PASSAR A QUARY PARA GERAR O RELATÓRIO PARA O PROGRAMADOR */

SELECT EMAIL, NOME, T.NUMERO FROM CLIENTE
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F' AND E.ESTADO = 'SP' AND T.TIPO = 'CEL';












