USE COMERCIO;

SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO
WHERE ID_CLIENTE = IDCLIENTE AND SEXO = 'F';

SELECT NOME, SEXO, E.BAIRRO, E.CIDADE FROM CLIENTE
INNER JOIN ENDERECO E
ON E.ID_CLIENTE = IDCLIENTE;

SELECT NOME, SEXO, E.BAIRRO, E.CIDADE 
FROM CLIENTE
INNER JOIN ENDERECO E
ON E.ID_CLIENTE = IDCLIENTE
WHERE SEXO = 'F';INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ');

SELECT NOME, SEXO, EMAIL, T.TIPO, T.NUMERO 
FROM CLIENTE
INNER JOIN TELEFONE T
ON T.ID_CLIENTE = IDCLIENTE;

SELECT NOME, SEXO, EMAIL, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO 
FROM CLIENTE
INNER JOIN ENDERECO E
ON E.ID_CLIENTE = IDCLIENTE
INNER JOIN TELEFONE T
ON T.ID_CLIENTE = IDCLIENTE;


/*
DML - DATA MANIPULATION LANGUAGE
DDL - DATA DEFINITION LANGUAGE
DCL - DATA CONTROL LANGUAGE
TCL - TRANSACTION CONTROL LANGUAGE
*/

#DML

/* INSERT */

INSERT INTO CLIENTE VALUES(NULL,'PAULA','M',NULL,'77437493');
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ',7);

SELECT * FROM CLIENTE;

/* FILTROS */
SELECT * FROM CLIENTE;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;

INSERT INTO CLIENTE VALUES(NULL,'XXXX','M',NULL,'77437492');

/*DELETE*/
DELETE FROM CLIENTE WHERE IDCLIENTE = 9;

/*
	DDL - DATA DEFINITION LANGUAGE
*/

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT,
    FRETE FLOAT(10,2) NOT NULL
);

# ALTER TABLE

# ALTERANDO O NOME DA COLUNO - CHANGE

ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

ALTER TABLE PRODUTO
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

# MODIFY - ALTERANDO O TIPO
ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;


# ADICIONANDO COLUNAS - ADD
ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

#APAGANDO COLUNA

ALTER TABLE PRODUTO
DROP COLUMN PESO;

# ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;
