# ------Modelagem Básica

# CLIENTE:

# NOME - CARACTER(30)
# CPF - NUMERICO(11)
# EMAIL - CARACTER(30)
# TELEFONE - CARACTER(30)
# ENDERECO -  CARACTER(100)
# SEXO - CARACTER(1)

#--------PROCESSO DE MODELAGEM

# MODELAGEM CONCEITUAL
# MODELAGEM LÓGICA
# MODELAGEM FÍSICA

# Iniciando a modelagem física

# CRIANDO BANCO

CREATE DATABASE PROJETO;

# CONECTANDO-SE AO BANCO

USE PROJETO;

#CRIANDO TABELA

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/*Mostrando as tabelas*/

SHOW tables;

/* exibindo a estrutura de uma tabela */

DESC CLIENTE;

#INSERINDO DADOS NA TABELA

/*FORMA 01 - OMITINDO AS COLUNAS*/

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - RJ');

/*FORMA 02 - COLOCANDO AS COLUNAS*/

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/*FORMA 03 - INSERT COMPACATO - SOMENTE MYSQL*/

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO -SAO PAULO - SP'),
('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/*Seleção projeção e junção*/

#Projeção


SELECT NOW();

SELECT 'FELIPE MAFRA';
SELECT 'BANCO DE DADOS';

/*ALIAS DE COLUNAS*/

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/*SELEÇÃO*/
/*FILTRAR*/

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

#UTILIZANDO O LIKE
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

#CARACTER CORINGA -> PODE SER QUALQUER COISA
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

